### ISSUE TITLE
offline secondary_path_identification issue

### ISSUE THREAD

**Issue by JaySpeech** [psykulsk/RpiANC#8]
Thanks for your sharing about ANC and I have a question.

In Mains/offline_sec_path_modelling.cpp
—————————————————————————————————————————————————-
secondary_path_identification(processing_buffer.data(), reference_generated_for_processing.data(),
                                                  BUFFER_SAMPLE_SIZE,  secondary_path_estimation_filter);

void secondary_path_identification(fixed_sample_type *samples_buffer, fixed_sample_type *ref_for_processing, long unsigned int buffer_length,
        LMSFilter<FX_FILTER_LENGTH> &sec_path_estimation_filter){
    for (unsigned long i = 1; i < buffer_length; i += 2) {
        sample_type error_sample = signed_fixed_to_floating(samples_buffer[i]);
        sample_type reference_sample =signed_fixed_to_floating(ref_for_processing[i - 1]);
        sec_path_estimation_filter.lms_step(reference_sample, error_sample, reference_sample);
    }
}
—————————————————————————————————————————————————-

reference_generated_for_processing is the white noise playback signal,  processing_buffer is the error mic signal. I think LMS should not use error mic data as error_sample.  The error_sample should be  ‘d(n)(error mic data)-y(n)(filter data)’ .

Scripts/OctaveCode/lms1.m
—————————————————————————————————————————————————-
y(n) = f_n.'*x_n;
e(n) = d(n) - y(n);
f_n = f_n + alpha*e(n)*x_n;
—————————————————————————————————————————————————-

Look forword for your reply.

**Comment by psykulsk** [comment]
Hello and thank you for your interest in this project! 

Small disclaimer at the beginning, I have not worked on ANC nor digital signal processing since finishing this project ~3-4 years ago, so I may be missing something :) 

I know this is not clear from the code, but I believe that in the end I used `Mains/offline_sec_path_modelling.cpp`  , `Mains/record_noise.cpp` or `Mains/record_test_data.cpp` only to record the white noise, without outputting any correction signal (as you can see in  `Mains/offline_sec_path_modelling.cpp`, the [processing buffer is never copied to the playback buffer](https://github.com/psykulsk/RpiANC/blob/8ca3f54cdfb90ca3bf31d492714851c919c5ae39/Mains/offline_sec_path_modelling.cpp#L109-L110), as it is done in the [Mains/feedforward_anc.cpp](https://github.com/psykulsk/RpiANC/blob/master/Mains/feedforward_anc.cpp#L133-L135)). Then I did offline secondary path modelling in octave, using `Scripts/OctaveCode/lms_offlince_sec_path_modelling.m` or `Scripts/OctaveCode/rls_offline_sec_path_modelling.m`), where the adaptive filter is supplied with the error signal calculated as you've described.

In a typical setup where an adaptive filter is used for unknown system identification, yes it is true that you have to use something like `e(n) = d(n) - y(n);` and provide that to the adaptive filter, as shown in the diagram below.


![image](https://github.com/psykulsk/RpiANC/assets/9095621/d606e706-1121-452c-b750-59043590b3f6)
[image source](https://www.mathworks.com/help/dsp/ug/overview-of-adaptive-filters-and-applications.html#f1-5547)

In the case of the active noise control system, the  `e(n) = d(n) - y(n);` part does not happen during digital signals processing, but the acoustic waves that carry the noise signal (`reference_generated_for_processing` noise in that case) and the output from the filter (emitted by the speaker) interfere and the error microphone captures the resulting `e(n)` signal.

![image](https://github.com/psykulsk/RpiANC/assets/9095621/eb550715-9d4e-4361-8841-fec38804e004)
[image source](https://www.researchgate.net/publication/260676810_FxLMS-based_active_noise_control_A_quick_review)

Maybe it is worth trying to modify this code to actually output the correction signal from the adaptive filter (noise would have to be played by a separate speaker though, as the playback device used here would have to emit only the correction signal) and this way the estimate of the secondary path would be more accurate.

I hope that helps!

**Comment by JaySpeech** [comment]
Thanks for your help. I am now start to debug the anc system.
