### ISSUE TITLE
How to understand the previous_reference_samples variable in the processing_feedforward_anc function?

### ISSUE THREAD

**Issue by zhuwengit** [psykulsk/RpiANC#9]
Hello, thank you for sharing your active noise reduction! There are some puzzles in the source code.
In the processing_feedforward_anc function, why is the reference signal passed into the fxlms_filter.lms_step() function the previous frame? Moreover, previous_reference_samples.at(i/2) and error_sample do not match up well.
I hope you can answer and reply, best wishes!

**Comment by psykulsk** [comment]
Hi! Yes, sorry, this part is not very clear. Basically, because we are working on buffered blocks of samples, error signal samples from the current samples buffer have been captured at the same time as the reference signal samples.  As, because of the buffering, the delay in the system is quite high, I think, through experiment, I found better stability when we feed the FxLMSFilter with the reference sample from the previous buffer (that's why it's first accessed here https://github.com/psykulsk/RpiANC/blob/e69bc8121e47be85b00a119241cae1f20d6971b8/Sources/processing.cpp#L54-L55 and then updated).

It's been quite a long time since I worked on that project so I don't really remember my reasoning here, so I would encourage anyone to change that and use reference and error samples both from the current buffer and see the effect of that on the adaptive algorithm. You can also check that using simulated signal and look at some plots by running https://github.com/psykulsk/RpiANC/blob/e69bc8121e47be85b00a119241cae1f20d6971b8/Mains/fxlmstest.cpp 

Hope that helps, thanks!

**Comment by zhuwengit** [comment]
Ok, thanks again for your reply, I understand, best wishes!
